import "./globals.css";
import { Inter } from "next/font/google";
// import { ChakraProvider } from "@chakra-ui/react";
import ReactQueryProvider from "./Providers";
import Link from "next/link";
import { HStack } from "@chakra-ui/react";
import NavContainer from "./navContainer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ChakraProvider> */}
        <ReactQueryProvider>
          <NavContainer />
          <main>{children}</main>
        </ReactQueryProvider>
        {/* </ChakraProvider> */}
      </body>
    </html>
  );
}
